src/exceptions/__init__.py,sha256=tPELg15Xgk-poKkVRXTX4jkSghJhFchJr1F1X8CXghY,21
src/exceptions/_main.py,sha256=rXL214ttrzfTjzQYGD4zgkg2SvKN1JOPr79-7GRCF9Q,13101
pyexcept-0.0.1.dist-info/METADATA,sha256=nGkWk4zD-2MQob2nKuAxZJ5i2IyGmOzqBqVhCk5GJmI,3323
pyexcept-0.0.1.dist-info/WHEEL,sha256=hKi7AIIx6qfnsRbr087vpeJnrVUuDokDHZacPPMW7-Y,87
pyexcept-0.0.1.dist-info/licenses/LICENSE,sha256=hIahDEOTzuHCU5J2nd07LWwkLW7Hko4UFO__ffsvB-8,34523
pyexcept-0.0.1.dist-info/RECORD,,
